# Generated by Django 3.2.9 on 2021-12-09 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_auto_20211209_0242'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('message', models.ManyToManyField(blank=True, to='base.Message')),
                ('participants', models.ManyToManyField(blank=True, related_name='conversation', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
