# Generated by Django 3.2.9 on 2021-12-09 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_conversation_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='id',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='id',
            new_name='msg_id',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='message',
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
