# Generated by Django 3.2.9 on 2021-12-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20211209_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='subject',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
