# Generated by Django 3.2.9 on 2021-12-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_conversation_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usertype',
            name='profile_image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
