# Generated by Django 3.2.9 on 2021-12-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20211210_0625'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertype',
            name='cover_image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
